version: '2.2'

services:
  BR01:
    image: frrouting/frr:v7.5.1
    hostname: BR01
    container_name: BR01
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/BR01:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      interas0:
        ipv4_address: "10.10.120.253"
        ipv6_address: "fc00:10:10:120::253"
      interas1:
        ipv4_address: "10.10.100.254"
        ipv6_address: "fc00:10:10:100::254"
      router1:
        ipv4_address: "10.10.0.14"
        ipv6_address: "fc00:10:10::14"
      router2:
        ipv4_address: "10.10.0.22"
        ipv6_address: "fc00:10:10:20::22"

  BR02:
    image: frrouting/frr:v7.5.1
    hostname: BR02
    container_name: BR02
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/BR02:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      interas0:
        ipv4_address: "10.10.120.254"
        ipv6_address: "fc00:10:10:120::254"
      interas2:
        ipv4_address: "10.10.200.254"
        ipv6_address: "fc00:10:10:200::254"
      router3:
        ipv4_address: "10.10.4.14"
        ipv6_address: "fc00:10:10:30::14"
      router4:
        ipv4_address: "10.10.4.22"
        ipv6_address: "fc00:10:10:40::22"

  BR03:
    image: frrouting/frr:v7.5.1
    hostname: BR03
    container_name: BR03
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/BR03:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      interas1:
        ipv4_address: "10.10.100.253"
        ipv6_address: "fc00:10:10:100::253"
      interas2:
        ipv4_address: "10.10.200.253"
        ipv6_address: "fc00:10:10:200::253"
      router5:
        ipv4_address: "10.10.8.14"
        ipv6_address: "fc00:10:10:50::14"
      router6:
        ipv4_address: "10.10.8.22"
        ipv6_address: "fc00:10:10:60::22"

  R1:
    image: frrouting/frr:v7.5.1
    hostname: R1
    container_name: R1
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/R1:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      router1:
        ipv4_address: "10.10.0.10"
        ipv6_address: "fc00:10:10::10"
      router12:
        ipv4_address: "10.10.0.2"
        ipv6_address: "fc00:10:10:12::2"
      client1:
        ipv4_address: "10.10.1.254"
        ipv6_address: "fc00:10:10:1::254"
 
  C1:
    image: jpetazzo/netshoot
    command: tail -f /dev/null
    hostname: C1
    container_name: C1
    privileged: true
    volumes:
      - ./hosts:/etc/hosts
    networks:
      client1:
        ipv4_address: "10.10.1.2"
        ipv6_address: "fc00:10:10:1::2"

  R2:
    image: frrouting/frr:v7.5.1
    hostname: R2
    container_name: R2
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/R2:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      router2:
        ipv4_address: "10.10.0.18"
        ipv6_address: "fc00:10:10:20::18"
      router12:
        ipv4_address: "10.10.0.6"
        ipv6_address: "fc00:10:10:12::6"
      client2:
        ipv4_address: "10.10.2.254"
        ipv6_address: "fc00:10:10:2::254"
 
  C2:
    image: jpetazzo/netshoot
    command: tail -f /dev/null
    hostname: C2
    container_name: C2
    privileged: true
    volumes:
      - ./hosts:/etc/hosts
    networks:
      client2:
        ipv4_address: "10.10.2.2"
        ipv6_address: "fc00:10:10:2::2"

  R3:
    image: frrouting/frr:v7.5.1
    hostname: R3
    container_name: R3
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/R3:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      router3:
        ipv4_address: "10.10.4.10"
        ipv6_address: "fc00:10:10:30::10"
      router34:
        ipv4_address: "10.10.4.2"
        ipv6_address: "fc00:10:10:34::2"
      client5:
        ipv4_address: "10.10.5.254"
        ipv6_address: "fc00:10:10:5::254"
 
  C5:
    image: jpetazzo/netshoot
    command: tail -f /dev/null
    hostname: C5
    container_name: C5
    privileged: true
    volumes:
      - ./hosts:/etc/hosts
    networks:
      client5:
        ipv4_address: "10.10.5.2"
        ipv6_address: "fc00:10:10:5::2"
  
  R4:
    image: frrouting/frr:v7.5.1
    hostname: R4
    container_name: R4
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/R4:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      router4:
        ipv4_address: "10.10.4.18"
        ipv6_address: "fc00:10:10:40::18"
      router34:
        ipv4_address: "10.10.4.6"
        ipv6_address: "fc00:10:10:34::6"
      client6:
        ipv4_address: "10.10.6.254"
        ipv6_address: "fc00:10:10:6::254"
 
  C6:
    image: jpetazzo/netshoot
    command: tail -f /dev/null
    hostname: C6
    container_name: C6
    privileged: true
    volumes:
      - ./hosts:/etc/hosts
    networks:
      client6:
        ipv4_address: "10.10.6.2"
        ipv6_address: "fc00:10:10:6::2"

  R5:
    image: frrouting/frr:v7.5.1
    hostname: R5
    container_name: R5
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/R5:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      router5:
        ipv4_address: "10.10.8.10"
        ipv6_address: "fc00:10:10:50::10"
      router56:
        ipv4_address: "10.10.8.2"
        ipv6_address: "fc00:10:10:56::2"
      client9:
        ipv4_address: "10.10.9.254"
        ipv6_address: "fc00:10:10:9::254"
 
  C9:
    image: jpetazzo/netshoot
    command: tail -f /dev/null
    hostname: C9
    container_name: C9
    privileged: true
    volumes:
      - ./hosts:/etc/hosts
    networks:
      client9:
        ipv4_address: "10.10.9.2"
        ipv6_address: "fc00:10:10:9::2"

  R6:
    image: frrouting/frr:v7.5.1
    hostname: R6
    container_name: R6
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    privileged: true
    volumes:
      - ./config/R6:/etc/frr
      - ./daemons:/etc/frr/daemons
      - ./hosts:/etc/hosts
    networks:
      router6:
        ipv4_address: "10.10.8.18"
        ipv6_address: "fc00:10:10:60::254"
      router56:
        ipv4_address: "10.10.8.6"
        ipv6_address: "fc00:10:10:56::254"
      client10:
        ipv4_address: "10.10.10.254"
        ipv6_address: "fc00:10:10:10::254"
 
  C10:
    image: jpetazzo/netshoot
    command: tail -f /dev/null
    hostname: C10
    container_name: C10
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    privileged: true
    volumes:
      - ./hosts:/etc/hosts
    networks:
      client10:
        ipv4_address: "10.10.10.2"
        ipv6_address: "fc00:10:10:10::2"

networks:
  interas0:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.120.0/24
        - subnet: fc00:10:10:120::/64
  interas1:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.100.0/24
        - subnet: fc00:10:10:100::/64
  interas2:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.200.0/24
        - subnet: fc00:10:10:200::/64
  router1:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.0.8/29
        - subnet: fc00:10:10::/64
  router2:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.0.16/29
        - subnet: fc00:10:10:20::/64
  router12:
    enable_ipv6: true
    ipam:
      config: 
        - subnet: 10.10.0.0/29
        - subnet: fc00:10:10:12::/64
  router3:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.4.8/29
        - subnet: fc00:10:10:30::/64
  router4:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.4.16/29
        - subnet: fc00:10:10:40::/64
  router34:
    enable_ipv6: true
    ipam:
      config: 
        - subnet: 10.10.4.0/29
        - subnet: fc00:10:10:34::/64
  router5:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.8.8/29
        - subnet: fc00:10:10:50::/64
  router6:
    enable_ipv6: true
    ipam: 
      config:
        - subnet: 10.10.8.16/29
        - subnet: fc00:10:10:60::/64
  router56:
    enable_ipv6: true
    ipam:
      config: 
        - subnet: 10.10.8.0/29
        - subnet: fc00:10:10:56::/64
  client1:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.10.1.0/24
        - subnet: fc00:10:10:1::/64
  client2:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.10.2.0/24
        - subnet: fc00:10:10:2::/64
  client5:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.10.5.0/24
        - subnet: fc00:10:10:5::/64
  client6:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.10.6.0/24
        - subnet: fc00:10:10:6::/64
  client9:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.10.9.0/24
        - subnet: fc00:10:10:9::/64
  client10:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.10.10.0/24
        - subnet: fc00:10:10:10::/64
